  version: '3'

  services:
    backend:
      build:
        context: ./backend
      environment:
        - SECRET_KEY=FOODIELABSPEPSI
      ports:
        - "5000"

    nginx:
      build:
        context: ./nginx
      ports:
        - "80:80"
        - "443:443"
      restart: always
      depends_on:
        - backend
      volumes:
        - ./data/certbot/conf:/etc/letsencrypt
        - ./data/certbot/www:/var/www/certbot     
        
    certbot:
      image: certbot/certbot
      volumes:
        - ./data/certbot/conf:/etc/letsencrypt
        - ./data/certbot/www:/var/www/certbot   
      entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

    frontend:
      build:
        context: ./frontend
      ports:
        - "9000"