version: '3.7'

services:
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=tecsifypasswordgenerico
      - MYSQL_DATABASE=certificados_tecsify
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql

  backend:
    build:
      context: ./backend
    environment:
      - SECRET_KEY=CERTIFICADOSTECSIFY
      - SQLALCHEMY_DATABASE_URI=mysql+pymysql://root:tecsifypasswordgenerico@mysql:3306/certificados_tecsify
    volumes:
      - ./backend:/backend
    ports:
      - "5000"

  nginx:
    build:
      context: ./nginx-dev
    ports:
      - "80:80"
    restart: always

  platform:
    image: php:apache
    volumes:
      - ./platform:/var/www/html
    ports:
      - "9000:80"