version: '3'

services:
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=tecsifypasswordgenerico
      - MYSQL_DATABASE=certificados_tecsify
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql

  backend:
    build:
      context: ./backend
    environment:
      - SECRET_KEY=CERTIFICADOSTECSIFY
      - SQLALCHEMY_DATABASE_URI=mysql+pymysql://root:tecsifypasswordgenerico@mysql:3306/certificados_tecsify
    ports:
      - "5000"
    depends_on:
      - backend
    volumes:
      - ./backend:/backend

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    links:
      - backend
    networks:
      - linklist_default
      - prodigy_default

  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    depends_on:
      - nginx
  
  platform:
    image: php:apache
    volumes:
      - ./platform:/var/www/html
    ports:
      - "9000:80"

  networks:
    linklist_default:
      external: true
    prodigy_default:
      external: true